# Generated by Django 5.0.3 on 2024-04-22 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadosexperiencia',
            fields=[
                ('idestado', models.IntegerField(db_column='IDEstado', primary_key=True, serialize=False)),
                ('designacao', models.CharField(blank=True, db_column='Designacao', max_length=25, null=True)),
            ],
            options={
                'db_table': 'estadosexperiencia',
            },
        ),
        migrations.CreateModel(
            name='Parametrosexperiencia',
            fields=[
                ('idparametros', models.AutoField(db_column='IDParametros', primary_key=True, serialize=False)),
                ('numeroratosinicial', models.IntegerField(db_column='NumeroRatosInicial')),
                ('limiteratossala', models.IntegerField(db_column='LimiteRatosSala')),
                ('segundossemmovimento', models.IntegerField(blank=True, db_column='SegundosSemMovimento', null=True)),
                ('temperaturaideal', models.DecimalField(db_column='TemperaturaIdeal', decimal_places=2, max_digits=4)),
                ('temperaturamaxima', models.DecimalField(db_column='TemperaturaMaxima', decimal_places=2, max_digits=4)),
                ('temperaturaminima', models.DecimalField(db_column='TemperaturaMinima', decimal_places=2, max_digits=4)),
                ('outliervariacaotempmax', models.FloatField(blank=True, db_column='OutlierVariacaoTempMax', null=True)),
                ('outlierleiturasnumero', models.IntegerField(blank=True, db_column='OutlierLeiturasNumero', null=True)),
                ('variacaodrasticatemperatura', models.FloatField(blank=True, db_column='VariacaoDrasticaTemperatura', null=True)),
                ('variacaodrasticaintervalotempo', models.IntegerField(blank=True, db_column='VariacaoDrasticaIntervaloTempo', null=True)),
            ],
            options={
                'db_table': 'parametrosexperiencia',
            },
        ),
        migrations.CreateModel(
            name='Tipoalerta',
            fields=[
                ('idtipoalerta', models.AutoField(db_column='IDTipoAlerta', primary_key=True, serialize=False)),
                ('designacao', models.CharField(db_column='Designacao', max_length=100)),
            ],
            options={
                'db_table': 'tipoalerta',
            },
        ),
        migrations.CreateModel(
            name='Tipoutilizador',
            fields=[
                ('idtipoutilizador', models.AutoField(db_column='IDTipoUtilizador', primary_key=True, serialize=False)),
                ('designacao', models.CharField(db_column='Designacao', max_length=40)),
            ],
            options={
                'db_table': 'tipoutilizador',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('idexperiencia', models.AutoField(db_column='IDExperiencia', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=50, null=True)),
                ('datahorainicio', models.DateTimeField(blank=True, db_column='DataHoraInicio', null=True)),
                ('datahorafim', models.DateTimeField(blank=True, db_column='DataHoraFim', null=True)),
                ('experienciavalida', models.IntegerField(blank=True, db_column='ExperienciaValida', null=True)),
                ('substancia', models.CharField(blank=True, db_column='Substancia', max_length=50, null=True)),
                ('isactive', models.IntegerField(blank=True, db_column='IsActive', null=True)),
                ('idestado', models.ForeignKey(blank=True, db_column='IDEstado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tailwaglabs.estadosexperiencia')),
                ('idparametros', models.ForeignKey(blank=True, db_column='IDParametros', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tailwaglabs.parametrosexperiencia')),
            ],
            options={
                'db_table': 'experiencia',
            },
        ),
        migrations.CreateModel(
            name='Medicoespassagens',
            fields=[
                ('idmedicao', models.AutoField(db_column='IDMedicao', primary_key=True, serialize=False)),
                ('salaorigem', models.IntegerField(db_column='SalaOrigem')),
                ('saladestino', models.IntegerField(db_column='SalaDestino')),
                ('hora', models.DateTimeField(db_column='Hora')),
                ('iserror', models.IntegerField(blank=True, db_column='IsError', null=True)),
                ('timestampregisto', models.DateTimeField(blank=True, db_column='TimestampRegisto', null=True)),
                ('idexperiencia', models.ForeignKey(db_column='IDExperiencia', on_delete=django.db.models.deletion.DO_NOTHING, to='tailwaglabs.experiencia')),
            ],
            options={
                'db_table': 'medicoespassagens',
            },
        ),
        migrations.CreateModel(
            name='Medicoessalas',
            fields=[
                ('idmedicao', models.AutoField(db_column='IDMedicao', primary_key=True, serialize=False)),
                ('numeroratosfinal', models.IntegerField(blank=True, db_column='NumeroRatosFinal', null=True)),
                ('sala', models.IntegerField(db_column='Sala')),
                ('iserror', models.IntegerField(db_column='IsError')),
                ('idexperiencia', models.ForeignKey(db_column='IDExperiencia', on_delete=django.db.models.deletion.DO_NOTHING, to='tailwaglabs.experiencia')),
            ],
            options={
                'db_table': 'medicoessalas',
            },
        ),
        migrations.CreateModel(
            name='Medicoestemperatura',
            fields=[
                ('idmedicao', models.AutoField(db_column='IDMedicao', primary_key=True, serialize=False)),
                ('hora', models.DateTimeField(db_column='Hora')),
                ('leitura', models.DecimalField(db_column='Leitura', decimal_places=2, max_digits=4)),
                ('sensor', models.IntegerField(blank=True, db_column='Sensor', null=True)),
                ('iserror', models.IntegerField(blank=True, db_column='IsError', null=True)),
                ('isoutlier', models.IntegerField(blank=True, db_column='IsOutlier', null=True)),
                ('timestampregisto', models.DateTimeField(blank=True, db_column='TimestampRegisto', null=True)),
                ('idexperiencia', models.ForeignKey(db_column='IDExperiencia', on_delete=django.db.models.deletion.DO_NOTHING, to='tailwaglabs.experiencia')),
            ],
            options={
                'db_table': 'medicoestemperatura',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('idalerta', models.AutoField(db_column='IDAlerta', primary_key=True, serialize=False)),
                ('hora', models.DateTimeField(db_column='Hora')),
                ('sala', models.IntegerField(db_column='Sala')),
                ('sensor', models.IntegerField(db_column='Sensor')),
                ('leitura', models.DecimalField(db_column='Leitura', decimal_places=2, max_digits=4)),
                ('mensagem', models.CharField(db_column='Mensagem', max_length=100)),
                ('horaescrita', models.DateTimeField(db_column='HoraEscrita')),
                ('idexperiencia', models.ForeignKey(db_column='IDExperiencia', on_delete=django.db.models.deletion.DO_NOTHING, to='tailwaglabs.experiencia')),
                ('tipoalerta', models.ForeignKey(db_column='TipoAlerta', on_delete=django.db.models.deletion.DO_NOTHING, to='tailwaglabs.tipoalerta')),
            ],
            options={
                'db_table': 'alerta',
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('telefone', models.CharField(db_column='Telefone', max_length=12)),
                ('isactive', models.IntegerField(blank=True, db_column='IsActive', null=True)),
                ('tipoutilizador', models.ForeignKey(db_column='TipoUtilizador', on_delete=django.db.models.deletion.DO_NOTHING, to='tailwaglabs.tipoutilizador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'utilizador',
            },
        ),
        migrations.AddField(
            model_name='experiencia',
            name='idinvestigador',
            field=models.ForeignKey(blank=True, db_column='IDInvestigador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tailwaglabs.utilizador'),
        ),
    ]
