# Generated by Django 5.0.3 on 2024-05-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailwaglabs', '0003_salas_ratos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicoestemperatura',
            name='timestampregisto',
            field=models.IntegerField(blank=True, db_column='TimestampRegisto', null=True),
        ),
        migrations.AlterModelTable(
            name='salas_ratos',
            table='salas_ratos',
        ),
    ]
