# Generated by Django 5.0.3 on 2024-05-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailwaglabs', '0004_remove_utilizador_isactive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salas_ratos',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='medicoestemperatura',
            name='timestampregisto',
            field=models.BigIntegerField(blank=True, db_column='TimestampRegisto', null=True),
        ),
    ]
